# Generated by Django 3.1 on 2021-04-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
