# Generated by Django 3.1 on 2021-04-21 10:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='tdescription',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
