# Generated by Django 3.1 on 2021-04-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='facebooklink',
            new_name='fblink',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='linkedinlink',
            new_name='linkedlink',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='twitterlink',
            new_name='twlink',
        ),
    ]
