# Generated by Django 3.1 on 2021-04-24 05:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_category_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_first',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 24, 5, 19, 49, 143738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 24, 5, 19, 49, 144664, tzinfo=utc)),
        ),
    ]
